### ISSUE TITLE
VKEY Floating values

### ISSUE THREAD

**Issue by d1runberg** [rwaldron/tessel-io#4] opened 2016-04-07 17:01 UTC
I have a SparkFun VKEY hooked up to the T2 and using tessel-io. I get a floating stream/signal of key presses when logged to the console when I am not even pressing / holding a key. My code works on an Arduino running J5 and the exact same code. It seems to be floating between the 11 key and the 12 key. 

Code:

var five = require('johnny-five');
var t2 = require('tessel-io');
var board = new five.Board({
    io: new t2()
});

//when the board is ready
board.on('ready', function(){
   //define component objects
   //keypad
   var keyPad = new five.Keypad({
      controller: "VKEY",
      pin: 'B1',
      keys: [
        ["!", "@", "#"],
        ["$", "%", "^"],
        ["&", "-", "+"],
        ["<", ">", "?"],
     ],

   });

   keyPad.on('press', function(data){
      console.log(data.which);
   })
});

I get: 

[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
[ '>' ]
[ '?' ]
......
...................

**Comment by rwaldron** [comment] 2016-04-09 14:40
Yikes, I'm traveling this weekend, but will dig into this as soon as I can on Monday

**Comment by rwaldron** [comment] 2016-04-09 15:46
Note to self/interested parties: I think this is likely caused by the differing aref voltage. We've

**Comment by rwaldron** [comment] 2016-04-09 15:50
Also, I didn't mean to close this :/

**Comment by rwaldron** [comment] 2016-04-09 21:19
It was as I suspected—I didn't have the 3.3V range in the Keypad controller for VKEY. The fix required two changes: 

- [Updates in Johnny-Five's Keypad class `VKEY` controller](https://github.com/rwaldron/johnny-five/commit/e15d10b1eb12d126eef12461b3b9783cbffb14bb)
- [Updates in Tessel-IO to define its `aref` property](https://github.com/rwaldron/tessel-io/commit/ede2543ca2c23fff6438532002d03fbfd81789d5#diff-3e60455fa28968c36a2fa52415a9cd9fR403)


Using the following program: 

```js
var five = require("johnny-five");
var Tessel = require("tessel-io");
var board = new five.Board({
  io: new Tessel()
});

board.on("ready", function() {
  var keypad = new five.Keypad({
    controller: "VKEY",
    pin: "a7",
    keys: [
      ["!", "@", "#"],
      ["$", "%", "^"],
      ["&", "-", "+"],
      ["<", ">", "?"],
    ]
  });

  keypad.on("press", function(event) {
    console.log(event);
  });
});
```

Test run results: 

```
rwaldron at nova in ~/robotz/vkey-test
$ rm -r node_modules/
rwaldron at nova in ~/robotz/vkey-test
$ npm install johnny-five tessel-io

> serialport@2.0.6 install /Users/rwaldron/robotz/vkey-test/node_modules/serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "/Users/rwaldron/robotz/vkey-test/node_modules/serialport/build/Release/node-v46-darwin-x64/serialport.node" is installed via remote
vkey-test@1.0.0 /Users/rwaldron/robotz/vkey-test
├── johnny-five@0.9.39  extraneous
└── tessel-io@0.3.0  extraneous

npm WARN vkey-test@1.0.0 No description
npm WARN vkey-test@1.0.0 No repository field.
rwaldron at nova in ~/robotz/vkey-test
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
INFO Writing project to RAM on bishop (1100.288 kB)...
INFO Deployed.
INFO Running index.js...
1460236580251 Device(s) Tessel 2 (bishop)
1460236580402 Connected Tessel 2 (bishop)
1460236580504 Repl Initialized
>> { type: 'down', which: [ '!' ], timestamp: 1460236582959 }
{ type: 'down', which: [ '@' ], timestamp: 1460236583829 }
{ type: 'down', which: [ '#' ], timestamp: 1460236584451 }
{ type: 'down', which: [ '$' ], timestamp: 1460236585313 }
{ type: 'down', which: [ '%' ], timestamp: 1460236586003 }
{ type: 'down', which: [ '^' ], timestamp: 1460236586767 }
{ type: 'down', which: [ '&' ], timestamp: 1460236587324 }
{ type: 'down', which: [ '-' ], timestamp: 1460236587770 }
{ type: 'down', which: [ '+' ], timestamp: 1460236588271 }
{ type: 'down', which: [ '<' ], timestamp: 1460236589020 }
{ type: 'down', which: [ '>' ], timestamp: 1460236589547 }
{ type: 'down', which: [ '?' ], timestamp: 1460236590130 }
{ type: 'down', which: [ '!' ], timestamp: 1460236594978 }
{ type: 'down', which: [ '@' ], timestamp: 1460236596453 }
{ type: 'down', which: [ '#' ], timestamp: 1460236596932 }
{ type: 'down', which: [ '$' ], timestamp: 1460236597415 }
{ type: 'down', which: [ '%' ], timestamp: 1460236598630 }
{ type: 'down', which: [ '^' ], timestamp: 1460236599350 }
{ type: 'down', which: [ '&' ], timestamp: 1460236600207 }
{ type: 'down', which: [ '-' ], timestamp: 1460236600866 }
{ type: 'down', which: [ '+' ], timestamp: 1460236601438 }
{ type: 'down', which: [ '<' ], timestamp: 1460236602118 }
{ type: 'down', which: [ '>' ], timestamp: 1460236602601 }
{ type: 'down', which: [ '?' ], timestamp: 1460236603082 }
^Crwaldron at nova in ~/robotz/vkey-test

**Closed by rwaldron** 2016-04-09 21:19 UTC

**Comment by rwaldron** [comment] 2016-04-10 04:36
I should align the alias event names with the event type
